name: 2021-06-14-uproot-awkward-columnar-hats
channels:
  - conda-forge
dependencies:
  - uproot
  - awkward
  - pyarrow
  - numpy
  - scipy
  - matplotlib
  - hist
  - numba
  - root
  - pip
  - pip:
      - particle
